powers:
  creeper:
    enabled: true
    drop-chance: 50
    price: 10
  enderman:
    enabled: true
    drop-chance: 80
    price: 5
  ghast:
    enabled: true
    drop-chance: 90
    price: 3
  squid:
    enabled: true
    drop-chance: 20
    price: 5
  horse:
    enabled: true
    drop-chance: 30
    price: 10
  spider:
    enabled: true
    drop-chance: 30
    price: 10
  cave_spider:
    enabled: true
    drop-chance: 60
    price: 5
  skeleton:
    enabled: true
    drop-chance: 20
    price: 15
ignore-creative-kills: true
disabled-worlds:
- MobArena
